### ISSUE TITLE
Question Regarding LogoutSuccessHandler

### ISSUE THREAD

**Issue by frost-byte** [eXtreme/symfony-2fa#1]
I'm also trying to create my own two factor provider in Symfony 5.2, using the scheb/2fa package.
When creating a LogoutSuccessHandler using your class, I'm getting a deprecation notice about the [LogoutSuccessHandlerInterface](https://github.com/eXtreme/symfony-2fa/blob/78c532a3f311ba5b56188068d54e3ff1c3bdcf20/src/Security/LogoutSuccessHandler.php#L12).

Are you experiencing any issues with that? The recommendation is to switch to using an [event](https://symfony.com/doc/current/reference/configuration/security.html#success-handler).

I'm having an issue similar to the one you mentioned [here](https://github.com/scheb/2fa/issues/42)
I had not implemented all of the handlers, but I had created my own GuardAuthenticator.
I had thought that I might not have created the correct Authentication Token, because onAuthenticationSuccess in Scheb\TwoFactorBundle\Security\TwoFactor\Provider\TwoFactorProviderPreparationListener was indicating that the Token was not a TwoFactorTokenInterface, and hterefore not supported.

**Comment by eXtreme** [comment]
@frost-byte 

Yes, `LogoutSuccessHandlerInterface` is deprecated and you should use an Event. This repository (which should had been deleted ;)) contains a demonstration project to find a bug causing https://github.com/scheb/2fa/issues/42 so I didn't bother to use the event.

A Logout Event Handler that contains the same logic as in [LogoutSuccessHandler](https://github.com/eXtreme/symfony-2fa/blob/78c532a3f311ba5b56188068d54e3ff1c3bdcf20/src/Security/LogoutSuccessHandler.php#L12) in this project could look like this:

```php
<?php

namespace App\Security;

use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;
use Symfony\Component\Security\Http\Event\LogoutEvent;

class LogoutEventHandler
{
    private $urlGenerator;

    public function __construct(UrlGeneratorInterface $urlGenerator)
    {
        $this->urlGenerator = $urlGenerator;
    }

    public function onLogoutEvent(LogoutEvent $event)
    {
        $defaultFormat = $event->getRequest()->getPreferredFormat();
        if (false === strpos($event->getRequest()->getRequestFormat($defaultFormat), 'json')) {
            return new RedirectResponse($this->urlGenerator->generate('home'), Response::HTTP_SEE_OTHER);
        }

        $event->setResponse(new JsonResponse([ 'success' => true ]));
    }
}
```

with service definition:

```yaml
    App\Security\LogoutEventHandler:
        tags:
            - name: 'kernel.event_listener'
              event: 'Symfony\Component\Security\Http\Event\LogoutEvent'
              method: onLogoutEvent
              dispatcher: security.event_dispatcher.main
```

(Or you could probably make the handler an event subscriber to leverage autowiring/autoconfiguration).

* * *

And as for the fix for the mentioned issue - you have to wait for a new Symfony release (5.2.2) because it is not out yet. :) I'm waiting too.

**Comment by frost-byte** [comment]
Thanks for providing a working example! I may not be facing the same issue that you did, I’m not using the new Authentication system, instead I’m using a Guard that I wrote.

My token may not be valid, but my auth flow seems to be working to the point that the 2fa code has been checked and confirmed to be valid.  My issue is now related to how my Vue front end isn’t updating after succeeding with the 2fa check.
